[package]
name = "community"
version = "1.0.0"
edition = "2021"
authors = ["The best developer ever"]

[dependencies]

ink = { version = "4.2.1", default-features = false }

scale = { package = "parity-scale-codec", version = "3", default-features = false, features = ["derive"] }
scale-info = { version = "2.6", default-features = false, features = ["derive"], optional = true }

# Include brush as a dependency and enable default implementation for PSP22 via brush feature
openbrush = { tag = "4.0.0", git = "https://github.com/Brushfam/openbrush-contracts", default-features = false, features = ["ownable"] }

# package contracts
nutritionist_nft = { path = "../nutritionist_nft", default-features = false, features = ["ink-as-dependency"] }
user_nft = { path = "../user_nft", default-features = false, features = ["ink-as-dependency"] }

[lib]
name = "community"
path = "lib.rs"


[features]
default = ["std"]
std = [
    "ink/std",
    "scale/std",
    "scale-info/std",

    "openbrush/std",
    "nutritionist_nft/std",
    "user_nft/std"
]
ink-as-dependency = []